---
version: "3"
services:
  frontend:
    build: ./codedoc-frontend
    image: frontend:latest
    expose:
      - "3000"
    ports:
      - "3000:3000"

  backend:
    build: ./codedoc-backend
    image: backend:latest
    expose:
      - "1234"
    ports:
      - "1234:1234"
